### ISSUE TITLE
Possible bug with xpose 4.7.0 readting output tables

### ISSUE THREAD

**Issue by MahmAbdelwahab** [UUPharmacometrics/xpose4#16]
Hello all,

There seems to be an issue with the new xpose version when reading NONMEM generated table files, it fails to read the entire data items from tab files, e.g in patab.csv file (where I output my model parameters) I have around 10 data items but it only reads a subset of them. however, when I try to read the files with read.nm.tables, I can see that all of the data items are read.

I'm attaching a subset of the output files for reproducibility 
[example.zip](https://github.com/UUPharmacometrics/xpose4/files/5000395/example.zip)

Thanks

Mahmoud

**Comment by certara-kniefort** [comment]
I am seeing this as well.  Specifically, it looks like the xpose.data function is not populating the object@Prefs@Xvardef$covariates slot correctly for some reason.  In attempt to troublshoot, I traced it down to the Data(xpdb#) <- tmp step within the xpose.data function, where temp is the object created with read.nm.tables (which looks ok and contains all data variables).   This step is where it seems to miss populating the obj@Prefs@Xvardef$covariates with all of the covariates.

Thanks,
Keith

**Comment by andrewhooker** [comment]
Thanks for the report.  I'll check it out tomorrow and get back to you.
Andy

**Comment by andrewhooker** [comment]
Hi.

This is an issue with the readr package (or maybe just how xpose4 uses the package). A quick fix is to use:

`xpdb <- xpose.data("126dd", tab.suffix = ".csv", method="slow")`

A fix to the code so that this will not be needed is coming later today.

**Comment by andrewhooker** [comment]
The problem that Keith (@certara-kniefort ) reports is not the same.  A workaround is to define your own covariate scope using code like this:

`xvardef(xpdb) <- c("covariates", c("AGE","SEX","WT","SOMETHING_ELSE"))`

**Comment by andrewhooker** [comment]
Latest commits to Xpose solve these problems.
