### ISSUE TITLE
xpose.VPC semi log plot for data with negative pi.ci

### ISSUE THREAD

**Issue by YGAZ** [UUPharmacometrics/xpose4#9]
I am trying to do VPC plot with semilog y axis using xpose.VPC function but the lower bound of pi.ci is below zero. Can you please tell me how to fix this problem? Thanks! 
Here is my code:
```
xpose.VPC(vpc.info=vpc_results.csv, vpctab=vpctab, logy = T)
```
And I received the following error message:
```
The PI.ci on the y-axis goes below zero.
This means that taking the log of this prediction
interval gives non-real numbers.
The plot will not be created.
```

**Comment by andrewhooker** [comment]
Hi

You need to simulate with a model that does not create negative values if you want to make plots on the log-scale.

Best regards,
Andrew
